# rules.py
# Attributes (plain): soft_bag, foam, greasy_or_wet, paper_cup, carton
# City keys are case-insensitive; unknown cities fall back to "default".

RULES = {
    "default": {
        "Plastic": {
            "soft_bag": "Drop-off",
            "foam": "Landfill",
            "default": "Recyclable",
        },
        "Paper": {
            "greasy_or_wet": "Landfill",
            "paper_cup": "Landfill",
            "carton": "Recyclable",
            "default": "Recyclable",
        },
        "Cardboard": {
            "greasy_or_wet": "Landfill",
            "default": "Recyclable",
        },
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },

    # --- Cities with curbside organics that accept food-soiled paper ---
    "austin": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "san francisco": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Compost", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "seattle": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Compost", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "portland": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "san jose": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "denver": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Recyclable", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },

    # --- Big cities (rules vary) ---
    "new york": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "los angeles": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "chicago": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "boston": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "philadelphia": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "houston": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "miami": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "phoenix": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "washington": {  # Washington, DC
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "atlanta": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Landfill", "paper_cup": "Landfill", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Landfill", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
    "minneapolis": {
        "Plastic": {"soft_bag": "Drop-off", "foam": "Landfill", "default": "Recyclable"},
        "Paper": {"greasy_or_wet": "Compost", "paper_cup": "Compost", "carton": "Recyclable", "default": "Recyclable"},
        "Cardboard": {"greasy_or_wet": "Compost", "default": "Recyclable"},
        "Metal": {"default": "Recyclable"},
        "Glass": {"default": "Recyclable"},
        "Trash": {"default": "Landfill"},
    },
}
